version: 2

models:
  - name: mart_listings_full
    description: "Tabela principal com dados de listings e ocupação do Airbnb Rio de Janeiro"
    columns:
      - name: listing_id
        description: "ID único do imóvel"
        tests:
          - unique
          - not_null

      - name: neighbourhood
        tests:
          - not_null

      - name: room_type
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['Entire home/apt', 'Private room', 'Shared room', 'Hotel room']

      - name: price
        tests:
          - not_null

      - name: occupancy_rate
        description: "Taxa de ocupação entre 0 e 1"

  - name: mart_listings_summary
    columns:
      - name: neighbourhood
        tests:
          - not_null

  - name: mart_seasonality
    description: "Análise de sazonalidade do Airbnb Rio de Janeiro por mês, bairro e tipo de quarto"
    columns:
      - name: year
        description: "Ano"
        tests:
          - not_null
      - name: month
        description: "Mês (1 a 12)"
        tests:
          - not_null
      - name: neighbourhood
        description: "Bairro do imóvel"
      - name: room_type
        description: "Tipo de quarto"
      - name: occupancy_rate
        description: "Taxa de ocupação entre 0 e 1"
      - name: total_revenue
        description: "Receita total realizada no período"
      - name: avg_price
        description: "Preço médio por noite"